### ISSUE TITLE
Не получается запустить примеры

### ISSUE THREAD

**Issue by zerobig** [megafonapi/examples#1]
**Проблема:** При попытке запуска любого примера возвращает код 403.
**Описание:** Первый запрос "login" отрабатывает корректно. А далее все запросы возвращают:
`{
    "status":403,
    "message":"",
    "errors":{},
    "success":false
}`

**Comment by enp** [comment]
"При попытке запуска любого примера" - это недостаточно информативно :) Как воспроизвести проблему?

**Comment by zerobig** [comment]
Хм. Казалось что достаточно подробно описал. Ладно, исправлюсь.
**Пример:** https://testapi.megafon.ru/v1/example/
![Screenshot_11](https://user-images.githubusercontent.com/3147314/82785755-e7733d80-9e6b-11ea-81eb-600a0a6c16e6.png)
![Screenshot_10](https://user-images.githubusercontent.com/3147314/82785772-f0640f00-9e6b-11ea-8b05-587812b6bde9.png)

**Comment by enp** [comment]
Да, так лучше: получается, что это не любой пример, а браузерный, и ошибка происходит на стадии получения токена, а с диагностикой на этом этапе у нас пока не все хорошо. Подозреваю, что у вас явным образом не включена услуга Пользователь Мегафон.API. Напишите полный номер (можно в личку или в https://web.telegram.org/#/im?p=@megafonapigroup) чтобы мы это исправили
